language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

sudo: false


install:
  - pip install --upgrade setuptools
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install mock
  - pip install -r requirements.txt
  - python setup.py develop


script:
  - flake8 pyaspeller tests
  - coverage run --source=pyaspeller setup.py test
  - python setup.py check -rm


after_success:
    coveralls